package MyJ_CommonLib;



public enum DbResultEnum
{
	RECODE_INIT,RECODE_FAILT
	,RECODE_OP_SECCUES
	, RECODE_HAVED,RECODE_NOTHAVED
	, RECODE_UPDATASECCUES,RECODE_UPDATAFAILT	
	, RECODE_DELETE
	, RECODE_EXCEPTION
	, RECODE_INSERT
	, RECODE_LOGON_OK,RECODE_LOGON_NAMEERR,RECODE_LOGON_PASSERR;
	public String MSG_RETURN=""; 
}

